### ISSUE TITLE
PUT or PATCH

### ISSUE THREAD

**Issue by paulohrodrigues** [mlabssoftware/mlabs-teste#3]
![image](https://user-images.githubusercontent.com/20190130/107385812-038a3e00-6ad2-11eb-8913-586704ce625b.png)

A descrição diz que tem que ser PUT, mas para esses casos eu penso que seria melhor o PATCH. Faz sentido?

**Comment by palloi** [comment]
@paulohrodrigues bom dia! 

Faz sentido em ser um patch, já que iremos atualizar somente alguns dados.

boa semana!

**Comment by paulohrodrigues** [comment]
thanks

**Comment by luiseduardogfranca** [comment]
> thanks

Boa sacada, mano!
